/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Response for cancelling a batch of orders
type UserBatchOrdersCancelSingleOrderResponse struct {
	Error_ *JsonError `json:"error,omitempty"`
	// ID of the order
	Id string `json:"id"`
	Order *Order `json:"order,omitempty"`
	// Result of the decrease operation
	ReducedBy int32 `json:"reduced_by,omitempty"`
}
