/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GetUserImmediateFundingResponse struct {
	DepositFeeCents int64 `json:"deposit_fee_cents"`
	ImmediateAmountBeingUsed int64 `json:"immediate_amount_being_used"`
	ImmediateAmountRemaining int64 `json:"immediate_amount_remaining"`
	ImmediateDepositAmount int64 `json:"immediate_deposit_amount"`
}
