/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// Represents a trade that can be displayed publicly. This does not include maker and taker information.  A trade is created whenever an order is fully or partially matched.
type PublicTrade struct {
	Count int32 `json:"count,omitempty"`
	CreateDate time.Time `json:"create_date,omitempty"`
	MarketId string `json:"market_id,omitempty"`
	Price int64 `json:"price,omitempty"`
	TradeId string `json:"trade_id,omitempty"`
}
