/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Response for submitting a batch of order
type UserBatchOrdersCreateResponse struct {
	// An array of responses corresponding to orders in the request.
	Orders []UserBatchOrdersCreateSingleOrderResponse `json:"orders"`
}
