/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ChangeSubscriptionRequest struct {
	PushPreferences bool `json:"push_preferences,omitempty"`
	// Specifies the subscription level for email notifications its values can be: \"none\", \"basic\" or \"all\"
	SubscriptionLevel string `json:"subscription_level"`
}
