/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GetUserWithdrawalsResponse struct {
	// List of previous withdrawals for the user
	Withdrawals []Withdrawal `json:"withdrawals"`
}
