/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Request for submitting a batch of orders
type UserBatchOrdersCreateRequest struct {
	// An array of individual orders to place
	Orders []UserOrderCreateRequest `json:"orders"`
}
