/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// Represents a trade from the user perspective.  A trade is created whenever an order is fully or partially matched, so there can be multiple trades with the same order_id. It is guaranteed that the sum of the count field for all the trades with the same order_id field shouldn't exceed the place_count on the order.
type UserTrade struct {
	Count int32 `json:"count,omitempty"`
	CreateDate time.Time `json:"create_date,omitempty"`
	Id string `json:"id,omitempty"`
	IsTaker bool `json:"is_taker,omitempty"`
	IsYes bool `json:"is_yes,omitempty"`
	MarketId string `json:"market_id,omitempty"`
	OrderId string `json:"order_id,omitempty"`
	Price int64 `json:"price,omitempty"`
	Status string `json:"status,omitempty"`
}
