/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UserChangePasswordRequest struct {
	// New password value.
	NewPassword string `json:"new_password"`
	// Old password should be passed as a validation parameter.
	OldPassword string `json:"old_password"`
}
