/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RangedMarketPosition struct {
	CollateralReturnedCents int64 `json:"collateral_returned_cents,omitempty"`
	MarketPositions []MarketPosition `json:"market_positions,omitempty"`
	RangedMarketId string `json:"ranged_market_id,omitempty"`
	UserId string `json:"user_id,omitempty"`
}
