/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AccountHistoryEntry struct {
	Data *AccountHistoryEntryData `json:"data,omitempty"`
	// Type of entry, one of Deposit, Withdrawal, Order, or Settlement
	Type_ string `json:"type"`
}
