/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// OrderBook Contains the number of pending resting order for each price on a specific market.
type OrderBook struct {
	No [][]int32 `json:"no"`
	Yes [][]int32 `json:"yes"`
}
