/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AccountHistoryEntryData struct {
	Credit *CreditHistory `json:"Credit,omitempty"`
	Deposit *DepositHistory `json:"Deposit,omitempty"`
	Order *OrderHistory `json:"Order,omitempty"`
	Settlement *SettlementHistory `json:"Settlement,omitempty"`
	Trade *TradeHistory `json:"Trade,omitempty"`
	Withdrawal *WithdrawalHistory `json:"Withdrawal,omitempty"`
}
