/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Response for login request
type LoginResponse struct {
	// Access level, to limit the access that applicants have
	AccessLevel string `json:"access_level"`
	// Access token for an member role session in the api
	Token string `json:"token"`
	// Your user_id, this will be required in all requests under the /users prefix
	UserId string `json:"user_id"`
}
