/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UserOrderDecreaseResponse struct {
	Order *Order `json:"order"`
	// Result of the decrease operation
	ReducedBy int32 `json:"reduced_by"`
}
