/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UserDepositResponse struct {
	Deposit *Deposit `json:"deposit,omitempty"`
	// Id for the deposit that was created.
	DepositId string `json:"deposit_id"`
	// The estimated number of days we believe the ach transfer will take
	EstimatedAchTimeDays int32 `json:"estimated_ach_time_days"`
}
