/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type SettlementHistory struct {
	DeterminedTime time.Time `json:"determined_time,omitempty"`
	MarketId string `json:"market_id,omitempty"`
	MarketResult string `json:"market_result,omitempty"`
	MarketTitle string `json:"market_title,omitempty"`
	NoCount int64 `json:"no_count,omitempty"`
	NoTotalCost int64 `json:"no_total_cost,omitempty"`
	Profit int64 `json:"profit,omitempty"`
	SettledTime time.Time `json:"settled_time,omitempty"`
	YesCount int64 `json:"yes_count,omitempty"`
	YesTotalCost int64 `json:"yes_total_cost,omitempty"`
}
