/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Series struct {
	FirstOpenDate time.Time `json:"first_open_date,omitempty"`
	Frequency string `json:"frequency,omitempty"`
	Ticker string `json:"ticker,omitempty"`
	Title string `json:"title,omitempty"`
}
