/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// Represents user orders in the api.  When an order is matched multiple trades can be created this can be tracked by looking into the trade.order_id field.
type Order struct {
	CloseCancelCount int32 `json:"close_cancel_count,omitempty"`
	CreateTs time.Time `json:"create_ts,omitempty"`
	DecreaseCount int32 `json:"decrease_count,omitempty"`
	ExpirationTs time.Time `json:"expiration_ts,omitempty"`
	ExtraCost int64 `json:"extra_cost,omitempty"`
	ExtraCount int32 `json:"extra_count,omitempty"`
	FccCancelCount int32 `json:"fcc_cancel_count,omitempty"`
	IsYes bool `json:"is_yes,omitempty"`
	LastUpdateOp string `json:"last_update_op,omitempty"`
	MakerFillCount int32 `json:"maker_fill_count,omitempty"`
	MarketId string `json:"market_id,omitempty"`
	OrderId string `json:"order_id,omitempty"`
	PlaceCount int32 `json:"place_count,omitempty"`
	Price int64 `json:"price,omitempty"`
	QueuePosition int32 `json:"queue_position,omitempty"`
	RemainingCount int32 `json:"remaining_count,omitempty"`
	Status string `json:"status,omitempty"`
	TakerFees int64 `json:"taker_fees,omitempty"`
	TakerFillCost int64 `json:"taker_fill_cost,omitempty"`
	TakerFillCount int32 `json:"taker_fill_count,omitempty"`
	UserId string `json:"user_id,omitempty"`
}
