/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// Represents a deposit.
type Deposit struct {
	AmountCents int64 `json:"amount_cents,omitempty"`
	BankId string `json:"bank_id,omitempty"`
	CreatedTs time.Time `json:"created_ts,omitempty"`
	DepositType string `json:"deposit_type,omitempty"`
	Id string `json:"id,omitempty"`
	ImmediateAmount int64 `json:"immediate_amount,omitempty"`
	ImmediateStatus string `json:"immediate_status,omitempty"`
	ReturnCode string `json:"return_code,omitempty"`
	ReturnReason string `json:"return_reason,omitempty"`
	Status string `json:"status,omitempty"`
	UserId string `json:"user_id,omitempty"`
}
