/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MarketStatsPoint struct {
	DollarOpenInterest int64 `json:"dollar_open_interest,omitempty"`
	DollarVolume int64 `json:"dollar_volume,omitempty"`
	OpenInterest int64 `json:"open_interest,omitempty"`
	Price int64 `json:"price,omitempty"`
	Ts int64 `json:"ts,omitempty"`
	Volume int64 `json:"volume,omitempty"`
	YesAsk int64 `json:"yes_ask,omitempty"`
	YesBid int64 `json:"yes_bid,omitempty"`
}
