/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// Represents a deposit account history item
type DepositHistory struct {
	Amount int64 `json:"amount,omitempty"`
	CreatedAt time.Time `json:"created_at,omitempty"`
	DepositType string `json:"deposit_type,omitempty"`
	Fee int64 `json:"fee,omitempty"`
	ImmediateAmount int64 `json:"immediate_amount,omitempty"`
	ImmediateStatus string `json:"immediate_status,omitempty"`
	ReturnedAmount int64 `json:"returned_amount,omitempty"`
	Status string `json:"status,omitempty"`
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
