/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type CreditHistory struct {
	AmountCents int64 `json:"amount_cents,omitempty"`
	CreatedAt time.Time `json:"created_at,omitempty"`
	Reason string `json:"reason,omitempty"`
	Status string `json:"status,omitempty"`
	Type_ string `json:"type,omitempty"`
}
