/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Encapsulates meta-data of bank accounts.  This is not stored within Kalshi, it is always proxied from the clearing house.
type BankAccountDetails struct {
	BankId string `json:"bank_id"`
	Mask string `json:"mask"`
	Name string `json:"name"`
	PlaidItemNeedsRelink bool `json:"plaid_item_needs_relink"`
	RoutingNumber string `json:"routing_number,omitempty"`
	Subtype string `json:"subtype"`
	Type_ string `json:"type"`
}
