/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UserWithdrawalRequest struct {
	AmountCents int64 `json:"amount_cents"`
	BankId string `json:"bank_id"`
	FeeCents int64 `json:"fee_cents"`
}
