/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type TradeHistory struct {
	Amount int64 `json:"amount,omitempty"`
	CreatedAt time.Time `json:"created_at,omitempty"`
	Fee int64 `json:"fee,omitempty"`
	IsYes bool `json:"is_yes,omitempty"`
	MarketId string `json:"market_id,omitempty"`
	MarketTitle string `json:"market_title,omitempty"`
	Price int64 `json:"price,omitempty"`
}
