/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UserWithdrawalAvailableBalanceResponse struct {
	AvailableBalanceCents int64 `json:"available_balance_cents"`
	WithdrawalFeeCents int64 `json:"withdrawal_fee_cents"`
}
