/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ConfirmPasswordResetRequest struct {
	// The new password.
	Password string `json:"password"`
	// UserUUID for your user. You can get this from the password reset link query parameter.
	UserId string `json:"user_id"`
}
