/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type OrderHistory struct {
	CanceledCount int64 `json:"canceled_count,omitempty"`
	CloseCancelCount int64 `json:"close_cancel_count,omitempty"`
	CreatedAt time.Time `json:"created_at,omitempty"`
	FccCanceledCount int64 `json:"fcc_canceled_count,omitempty"`
	FilledCount int64 `json:"filled_count,omitempty"`
	IsYes bool `json:"is_yes,omitempty"`
	MarketId string `json:"market_id,omitempty"`
	MarketTitle string `json:"market_title,omitempty"`
	OriginalCount int64 `json:"original_count,omitempty"`
	Price int64 `json:"price,omitempty"`
	RemainingCount int64 `json:"remaining_count,omitempty"`
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
