/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Request for cancelling a batch of orders
type UserBatchOrdersCancelRequest struct {
	// An array of order IDs to cancel
	Ids []string `json:"ids"`
}
