/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UserWithdrawalResponse struct {
	Withdrawal *Withdrawal `json:"withdrawal,omitempty"`
	// Id for the withdrawal that was created.
	WithdrawalId string `json:"withdrawal_id"`
}
