/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// Request for fetching user portfolio history
type UserGetPortfolioHistoryRequest struct {
	// Restricts the response to orders before a timestamp in: query
	MaxDate time.Time `json:"max_date,omitempty"`
	// Restricts the response to orders before a timestamp in unix seconds, overrides max_date, defaults to now. in: query
	MaxTs int64 `json:"max_ts,omitempty"`
	// Restricts the response to orders after a timestamp in: query
	MinDate time.Time `json:"min_date,omitempty"`
	// Restricts the response to orders after a timestamp in unix seconds, overrides min_date, defaults to one hour before now. in: query
	MinTs int64 `json:"min_ts,omitempty"`
	// Determines the number of buckets to average over when performing subsampling, defaults to 1440. in: query
	NumBuckets int32 `json:"num_buckets,omitempty"`
}
