/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MarketHistoryCandleStickInfo struct {
	EndTs int64 `json:"EndTs,omitempty"`
	OpenInterest int64 `json:"OpenInterest,omitempty"`
	Price *Olhcm `json:"Price,omitempty"`
	StartTs int64 `json:"StartTs,omitempty"`
	Volume int64 `json:"Volume,omitempty"`
	YesAsk *Olhcm `json:"YesAsk,omitempty"`
	YesBid *Olhcm `json:"YesBid,omitempty"`
}
