/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type MarketTransaction struct {
	AveragePrice int64 `json:"average_price,omitempty"`
	Fee int64 `json:"fee,omitempty"`
	IsSideYes bool `json:"is_side_yes,omitempty"`
	MarketId string `json:"market_id,omitempty"`
	MarketTicker string `json:"market_ticker,omitempty"`
	MarketTitle string `json:"market_title,omitempty"`
	NumContracts int64 `json:"num_contracts,omitempty"`
	RealizedCostOfContracts int64 `json:"realized_cost_of_contracts,omitempty"`
	RealizedFifoProfit int64 `json:"realized_fifo_profit,omitempty"`
	RealizedRevenue int64 `json:"realized_revenue,omitempty"`
	Time time.Time `json:"time,omitempty"`
	Type_ string `json:"type,omitempty"`
}
