/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// MarketPosition is your accumulated position on a specific market considering all orders and trades.
type MarketPosition struct {
	FeesPaid int64 `json:"fees_paid,omitempty"`
	// Settlement stats
	FinalPosition int32 `json:"final_position,omitempty"`
	FinalPositionCost int64 `json:"final_position_cost,omitempty"`
	IsSettled bool `json:"is_settled,omitempty"`
	MarketId string `json:"market_id,omitempty"`
	// Current stats
	Position int32 `json:"position,omitempty"`
	PositionCost int64 `json:"position_cost,omitempty"`
	RealizedPnl int64 `json:"realized_pnl,omitempty"`
	RestingOrdersCount int32 `json:"resting_orders_count,omitempty"`
	TotalCost int64 `json:"total_cost,omitempty"`
	UserId string `json:"user_id,omitempty"`
	Volume int32 `json:"volume,omitempty"`
}
