/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type MarketActivity struct {
	CloseDate time.Time `json:"close_date,omitempty"`
	MarketId string `json:"market_id,omitempty"`
	OpenDate time.Time `json:"open_date,omitempty"`
	PriceChange int64 `json:"price_change,omitempty"`
	Ticker string `json:"ticker,omitempty"`
	VolumeIncrease int32 `json:"volume_increase,omitempty"`
}
