/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type PeopleReferred struct {
	Email string `json:"email,omitempty"`
	ReferralId string `json:"referral_id,omitempty"`
	StageInFunnel string `json:"stage_in_funnel,omitempty"`
	TimeOfReferralExpiration time.Time `json:"time_of_referral_expiration,omitempty"`
}
