/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type EventChildMarket struct {
	CanCloseEarly bool `json:"can_close_early,omitempty"`
	CloseDate time.Time `json:"close_date,omitempty"`
	CloseUnconfirmed bool `json:"close_unconfirmed,omitempty"`
	CreateDate time.Time `json:"create_date,omitempty"`
	DollarOpenInterest int64 `json:"dollar_open_interest,omitempty"`
	DollarRecentVolume int64 `json:"dollar_recent_volume,omitempty"`
	DollarVolume int64 `json:"dollar_volume,omitempty"`
	ExpirationDate time.Time `json:"expiration_date,omitempty"`
	ExpirationValue string `json:"expiration_value,omitempty"`
	Id string `json:"id,omitempty"`
	LastPrice int64 `json:"last_price,omitempty"`
	Liquidity int64 `json:"liquidity,omitempty"`
	ListDate time.Time `json:"list_date,omitempty"`
	MiniTitle string `json:"mini_title,omitempty"`
	OpenDate time.Time `json:"open_date,omitempty"`
	OpenInterest int64 `json:"open_interest,omitempty"`
	PreviousPrice int64 `json:"previous_price,omitempty"`
	PreviousYesAsk int64 `json:"previous_yes_ask,omitempty"`
	PreviousYesBid int64 `json:"previous_yes_bid,omitempty"`
	RecentVolume int64 `json:"recent_volume,omitempty"`
	Result string `json:"result,omitempty"`
	RulebookVariables map[string]string `json:"rulebook_variables,omitempty"`
	Status string `json:"status,omitempty"`
	SubTitle string `json:"sub_title,omitempty"`
	TickerName string `json:"ticker_name,omitempty"`
	Title string `json:"title,omitempty"`
	Volume int64 `json:"volume,omitempty"`
	YesAsk int64 `json:"yes_ask,omitempty"`
	YesBid int64 `json:"yes_bid,omitempty"`
}
