/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Notification struct {
	Content map[string]interface{} `json:"content,omitempty"`
	CreatedTs time.Time `json:"created_ts,omitempty"`
	Id string `json:"id,omitempty"`
	IsDelivered bool `json:"is_delivered,omitempty"`
	IsRead bool `json:"is_read,omitempty"`
	Link string `json:"link,omitempty"`
	Type_ string `json:"type,omitempty"`
	UserId string `json:"user_id,omitempty"`
}
