/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Request for submitting an order
type UserOrderCreateRequest struct {
	// Specifies how many contracts should be bought
	Count int32 `json:"count"`
	// Specifies the expiration time of the order, in unix seconds.  If this is not supplied, or is 0, the order won't expire.
	ExpirationUnixTs int64 `json:"expiration_unix_ts,omitempty"`
	// Specifies the id of the market for this order
	MarketId string `json:"market_id"`
	MaxCostCents int64 `json:"max_cost_cents,omitempty"`
	Price int64 `json:"price"`
	// Specifies whether the order place count should be capped by the members current position.
	SellPositionCapped bool `json:"sell_position_capped,omitempty"`
	// Specifies if this is a 'yes' or 'no' order
	Side string `json:"side"`
}
