/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Portfolio measurement is simply a snapshot of the portfolio of a user on a timestamp.
type PortfolioMeasurement struct {
	A int64 `json:"a"`
	BalanceChange int64 `json:"balance_change,omitempty"`
	CumulativeDeposits int64 `json:"cumulative_deposits"`
	// Count of settlements member has had from account creation to timestamp (inclusive)
	CumulativeNumberSettlements int64 `json:"cumulative_number_settlements"`
	CumulativeWithdrawals int64 `json:"cumulative_withdrawals"`
	// Reason for the portfolio value change, if applicable
	Reason string `json:"reason,omitempty"`
	// Timestamp of the read in UNIX timestamp. (https://www.unixtimestamp.com/)
	Ts int64 `json:"ts"`
	V int64 `json:"v"`
}
