/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SubscriptionPreference struct {
	PushPreferences []string `json:"push_preferences,omitempty"`
	SubscriptionLevel string `json:"subscription_level,omitempty"`
}
