/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// Represents a user's profile on the api.
type User struct {
	AreaCode string `json:"area_code,omitempty"`
	BirthDate string `json:"birth_date,omitempty"`
	City string `json:"city,omitempty"`
	Country string `json:"country,omitempty"`
	CountryCode string `json:"country_code,omitempty"`
	CreatedTs time.Time `json:"created_ts,omitempty"`
	Email string `json:"email,omitempty"`
	FinishedFre bool `json:"finished_fre,omitempty"`
	FirstName string `json:"first_name,omitempty"`
	LastName string `json:"last_name,omitempty"`
	PhoneNumber string `json:"phone_number,omitempty"`
	PostalCode string `json:"postal_code,omitempty"`
	State string `json:"state,omitempty"`
	Street1 string `json:"street1,omitempty"`
	Street2 string `json:"street2,omitempty"`
	UseBidAsk bool `json:"use_bid_ask,omitempty"`
	UserId string `json:"user_id,omitempty"`
	Watchlist []string `json:"watchlist,omitempty"`
	WireCode string `json:"wire_code,omitempty"`
}
