/*
 * Kalshi API.
 *
 * This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// Market details
type Market struct {
	CanCloseEarly bool `json:"can_close_early,omitempty"`
	Category string `json:"category,omitempty"`
	CloseDate time.Time `json:"close_date,omitempty"`
	CloseUnconfirmed bool `json:"close_unconfirmed,omitempty"`
	CreateDate time.Time `json:"create_date,omitempty"`
	DescriptionCaseNo string `json:"description_case_no,omitempty"`
	DescriptionCaseYes string `json:"description_case_yes,omitempty"`
	DescriptionContext string `json:"description_context,omitempty"`
	DollarOpenInterest int64 `json:"dollar_open_interest,omitempty"`
	DollarRecentVolume int64 `json:"dollar_recent_volume,omitempty"`
	DollarVolume int64 `json:"dollar_volume,omitempty"`
	ExpirationDate time.Time `json:"expiration_date,omitempty"`
	ExpirationValue string `json:"expiration_value,omitempty"`
	FrequencyInDays int32 `json:"frequency_in_days,omitempty"`
	Id string `json:"id,omitempty"`
	ImageUrl string `json:"image_url,omitempty"`
	LastPrice int64 `json:"last_price,omitempty"`
	Liquidity int64 `json:"liquidity,omitempty"`
	ListDate time.Time `json:"list_date,omitempty"`
	MetricsTags []string `json:"metrics_tags,omitempty"`
	MinTickSize string `json:"min_tick_size,omitempty"`
	MiniTitle string `json:"mini_title,omitempty"`
	OpenDate time.Time `json:"open_date,omitempty"`
	OpenInterest int64 `json:"open_interest,omitempty"`
	OptionType string `json:"option_type,omitempty"`
	OriginalExpirationDate time.Time `json:"original_expiration_date,omitempty"`
	PreviousPrice int64 `json:"previous_price,omitempty"`
	PreviousYesAsk int64 `json:"previous_yes_ask,omitempty"`
	PreviousYesBid int64 `json:"previous_yes_bid,omitempty"`
	RangedGroupName string `json:"ranged_group_name,omitempty"`
	RangedGroupTicker string `json:"ranged_group_ticker,omitempty"`
	RecentVolume int64 `json:"recent_volume,omitempty"`
	Result string `json:"result,omitempty"`
	RulebookVariables map[string]string `json:"rulebook_variables,omitempty"`
	SettleDetails string `json:"settle_details,omitempty"`
	SettlementSources []SettlementSource `json:"settlement_sources,omitempty"`
	Status string `json:"status,omitempty"`
	StrikePrice float64 `json:"strike_price,omitempty"`
	SubTitle string `json:"sub_title,omitempty"`
	Tags []string `json:"tags,omitempty"`
	TickerName string `json:"ticker_name,omitempty"`
	Title string `json:"title,omitempty"`
	Underlying string `json:"underlying,omitempty"`
	Volume int64 `json:"volume,omitempty"`
	YesAsk int64 `json:"yes_ask,omitempty"`
	YesBid int64 `json:"yes_bid,omitempty"`
}
